### ISSUE TITLE
After closing certain dialogs, requests from the SDK no longer go through to Connect

### ISSUE THREAD

**Issue by lifang1984** [IBM/aspera-connect-sdk-js#12]
I use the "startTransfer" method to download the same file again, the Aspera Connect pop up a confirm dialog "There is an item with the same file name locally, do you want to continue?"
If click "No", then use "startTransfer" method to download others files, The system will no longer pop up the "IBM Aspera Connect" window

**Comment by dwosk** [comment]
Hi @lifang1984 I took a quick look and I saw the same thing. There is a known issue where the Connect client does not return a response if certain dialogs are closed/dismissed, such as this destination collision dialog.

A simple repro:
```javascript
let connectClient = new AW4.Connect();
connectClient.initSession();

let downloadSpec = {
    "paths": [
        {
            "source": "200KB.2"
        }
    ],
    "remote_host": "demo.asperasoft.com",
    "remote_user": "asperaweb",
    "authentication": "password",
    "remote_password": "demoaspera",
    "direction": "receive",
    "source_root": "aspera-test-dir-tiny"
}

// Download the 200KB.2 file.
connectClient.startTransfer(downloadSpec, {}, {});
// Once the transfer is finished, kick off another download of 200KB.2
// but choose 'No' in the collison dialog.
connectClient.startTransfer(downloadSpec, {}, {});
// Attempt to start another download.
connectClient.startTransfer(downloadSpec, {}, {});
// Result: Connect does not process new requests
```

I tried the same as above, but this time using the HTTP method (instead of extension), via just changing this one line:
```javascript
let connectClient = new AW4.Connect({ connectMethod: 'http' });
```
Using the HTTP method, I did not see this issue and I was able to kick off transfers and other requests even after selecting 'No' in the collison dialog.

I will need to do some more investigation to see if the bug is caused by the Connect SDK or how we handle requests in the native messaging host.

**Comment by lifang1984** [comment]
Thank you very much for your quick reply. 

I will use the way you suggested first.
let connectClient = new AW4.Connect({ connectMethod: 'http' });

**Comment by dwosk** [comment]
@lifang1984 after some more investigation it appears that this is a bug on the Connect client side and not the SDK. From the SDK side, we properly kick off requests and send them to the extension even when previous requests have not yet returned a response. I tested this with an older version of the SDK (3.11.2) and I see the same thing.

On the command line via cURL, I see that these transfer requests hang when the dialog is dismissed. However, if I open up another terminal session, I'm still able to get responses from the Connect API when doing additional transfer requests. This is the same behavior I see in the SDK when using the HTTP method instead of using the extension.

The fact that additional HTTP requests are able to go through but additional extension requests are not leads me to believe that the problem is in the native messaging host.

So, we'll have to fix in this in the Connect application itself, and there isn't much we can do here in the SDK.

**Comment by lifang1984** [comment]
Thank you!
