### ISSUE TITLE
Upload file failed by drag and drop

### ISSUE THREAD

**Issue by nawrockiLukasz** [IBM/aspera-connect-sdk-js#45]
Hi everyone, I have problem with upload by drag&drop files on Ubuntu, MacOS and probably Windows.

Upload file via asper dialog works perfectly.
But when I use method: **setDragDropTargets**([doc](https://ibm.github.io/aspera-connect-sdk-js/AW4.Connect.html#setDragDropTargets)) for uploading the same file, an error is returned:
```
{
 error: {
  code: 406,
  internal_message: "Not Acceptable",
  user_message: "can't upload unauthorized file \\"totest.png\\""
 }
}
```

The only difference in the transfer that I can see between these upload methods is the path to the file:
```
#Dialog upload config paths
{
  ...
  paths: [
   {source: '/home/vida/Obrazy/Zrzuty ekranu/totest.png', destination: '865038bd-0cc3-47c5-8c54-9632d943b526.png'}
  ],
  ...
}

**it's work**
```

```
#Drag&Drop upload config paths
{
 ...
 paths: [
  {source: 'totest.png', destination: 'f0faef6a-359d-4a67-b6d0-21528f3c7a3c.png'}
 ],
 ...
}

**It doesn't work**
```

Has anyone faced a similar problem or know a solution for this case?

**Comment by nawrockiLukasz** [comment]
It is true that the drag and drop function does not work without it. I have it configured.
Problem is:
file upload by drop event fails with the error message I've attached above
```
{
 error: {
  code: 406,
  internal_message: "Not Acceptable",
  user_message: "can't upload unauthorized file \\"totest.png\\""
 }
}
```

**Comment by dwosk** [comment]
`setDragDropTargets` takes in a callback that is called when a file is dropped on the target. Make sure that the transfer spec that you are constructing for the upload uses the absolute path to the dropped file that is available in this callback. It must be an absolute path, otherwise you will get this error.

In your snippet, the `source` field in ` paths` is not absolute so I would expect it to fail.

For example, with Connect 4.2.5 on macOS, when I drop a file named `foo.jpg` on a drag drop target, I see my callback is called with the following result:
```json
{
    "dataTransfer": {
        "files": [
            {
                "lastModifiedDate": "Fri May 05 13:00:04 2023",
                "name": "/Users/dwosk/Desktop/foo.jpg",
                "size": 420086,
                "type": "image/jpeg"
            }
        ]
    }
}
```

Notice the `name` field is an absolute path to the dropped file, and that is what would be used as the `source` field in `paths`.
