### ISSUE TITLE
 Compatibility Aspera HST Endpoint and Aspera Connect SDK

### ISSUE THREAD

**Issue by jhrunning** [IBM/aspera-connect-sdk-js#57]
Hello,

Currently, all customers who use the Aspera Connect SDK have installed the Aspera HST Server and are working with the Connect SDK.
We have a server with HST Endpoint 4.4.1 installed, could we use the Aspera Connect SDK with HST endpoint?

Thank you

**Comment by dwosk** [comment]
@jhrunning currently the Connect SDK only allows interacting with the Aspera Connect app. It does not support interacting with the Node API to do things like generate transfer specs, etc.

As far as licensing goes, I am not 100% sure if Aspera Connect is compatible with HSTE or not. From what I've gathered looking at the license, HSTE disables usage of Aspera Connect although I am not sure if that prevents Aspera Connect from doing transfers to/from the server.

**Comment by laurent-martin** [comment]
Up until Connect version 4.0 (not included), use of Connect client with Aspera Endpoint (HSTE, or , previously, Point to point) was not granted by the license file. (the license file of connect required that server had "connect enabled").
Since Connect version 4.x, the license file of connect does not require anymore that the server is "connect enabled", so although HSTE license is not "connect enabled" , the connect client version 4.x will be able to transfer to HSTE.
I got confirmation recently from product manager.
Note also that any limitation in use would be listed in the "License Information" document for the software, found at: IBM Terms: https://www.ibm.com/terms

**Comment by dwosk** [comment]
Perfect, thanks for the clarification @laurent-martin.

**Comment by jhrunning** [comment]
@dwosk @laurent-martin Thank you for your answer. It helped me a lot.
